### ISSUE TITLE
Autocomplete not working on windows

### ISSUE THREAD

**Issue by ryn1x** [vishnevskiy/ElixirSublime#40]
I added the bin path as the troubleshooting describes but it is still not working. I have installed on both Windows and macOS and I only have this problem on Windows.

In my user setting:

```
"env":
{
    "PATH": "C:\\Program Files (x86)\\Elixir\\bin"
},
```

The first time a type a letter after starting Sublime I get:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\ElixirSublime\elixir_sublime.py", line 268, in on_query_completions
    session = ElixirSession.ensure(os.path.dirname(view.file_name()))
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\ElixirSublime\elixir_sublime.py", line 160, in ensure
    session.connect()
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\ElixirSublime\elixir_sublime.py", line 179, in connect
    self.socket, _ = _socket.accept()
  File "./python3.3/socket.py", line 135, in accept
socket.timeout: timed out
```

And then I get this every letter thereafter:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\ElixirSublime\elixir_sublime.py", line 270, in on_query_completions
    if not session.send('COMPLETE', expand_selection(view, locations[0], aliases=aliases)):
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\ElixirSublime\elixir_sublime.py", line 189, in send
    self.socket.send(str.encode(cmd))
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by ryn1x** [comment]
I resolved this issue. I had to add "HEX_UNSAFE_HTTPS=1" as an Environment Variable and then run "mix deps.get" in my "sublime_completion" folder. It was an issue with my corporate proxy and CA certificate.
